name: Release

on:
  release:
    types: [published]

jobs:
  deploy:
    name: 'Deploy bundle'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy DAB
        run: databricks bundle deploy
        working-directory: .
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          #DATABRICKS_CLIENT_ID:  ${{ secrets.DATABRICKS_CLIENT_ID }} # recommended if you have necessary level permissions
          #DATABRICKS_CLIENT_SECRET:  ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          DATABRICKS_BUNDLE_ENV: prod

  update_app:
    name: 'Run bundle'
    runs-on: ubuntu-latest

    needs:
      - deploy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Set up Databricks CLI
        uses: databricks/setup-cli@main

      - name: Run DAB
        run: databricks bundle run genie_bot_app
        working-directory: .
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          #DATABRICKS_CLIENT_ID:  ${{ secrets.DATABRICKS_CLIENT_ID }}
          #DATABRICKS_CLIENT_SECRET:  ${{ secrets.DATABRICKS_CLIENT_SECRET }}
          DATABRICKS_BUNDLE_ENV: prod
